# Generated by Django 5.1.2 on 2024-10-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adrese',
            fields=[
                ('nume_adresa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tara', models.CharField(max_length=50)),
                ('judet', models.CharField(max_length=50)),
                ('localitate', models.CharField(max_length=50)),
                ('strada', models.CharField(max_length=50)),
                ('bloc', models.CharField(max_length=50)),
                ('scara', models.CharField(max_length=50)),
                ('etaj', models.PositiveIntegerField()),
                ('apartament', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'adrese',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comenzi',
            fields=[
                ('comanda_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_plasare', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comenzi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentiiLivrare',
            fields=[
                ('agentie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_agentie_livrare', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'agentii_livrare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarduriClienti',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('denumire', models.CharField(max_length=50)),
                ('numar_card', models.CharField(max_length=50)),
                ('nume_proprietar', models.CharField(max_length=50)),
                ('data_expirare', models.DateField()),
                ('tip_card', models.CharField(max_length=50)),
                ('banca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'carduri_clienti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_categorie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('parola_crypted', models.CharField(max_length=50)),
                ('numar_telefon', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clienti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Furnizori',
            fields=[
                ('furnizor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nume_furnizor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'furnizori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('produs_id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('stoc', models.SmallIntegerField()),
                ('pret_unitar', models.FloatField()),
            ],
            options={
                'db_table': 'produse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdreseComenzi',
            fields=[
                ('comanda_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.comenzi')),
                ('tara', models.CharField(max_length=50)),
                ('judet', models.CharField(max_length=50)),
                ('localitate', models.CharField(max_length=50)),
                ('strada', models.CharField(max_length=50)),
                ('bloc', models.CharField(max_length=50)),
                ('scara', models.CharField(max_length=50)),
                ('etaj', models.PositiveIntegerField()),
                ('apartament', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'adrese_comenzi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plati',
            fields=[
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.comenzi')),
                ('suma', models.FloatField()),
                ('metoda_plata', models.CharField(max_length=50)),
                ('data_plata', models.DateField()),
            ],
            options={
                'db_table': 'plati',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduseComenzi',
            fields=[
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.comenzi')),
                ('cantitate_comanda', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'produse_comenzi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cosuri',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.clienti')),
                ('cantitate_cos', models.IntegerField()),
                ('data_adaugare', models.DateField()),
            ],
            options={
                'db_table': 'cosuri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProprietatiProduse',
            fields=[
                ('produs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.produse')),
                ('dimensiune', models.CharField(max_length=50)),
                ('culoare', models.CharField(max_length=50)),
                ('tip_foaie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proprietati_produse',
                'managed': False,
            },
        ),
    ]
